Introduction:
  
  To simply say that the average fertility rate has declined over time would be a gross understatement, as the average rate has fallen by more than fifty percent in the last sixty years (Roser). The decline of fertility rates across the world remains of particular interest to scientists, economists, and policymakers since it is a multifaceted subject that seems to possess strong correlational ties to both social and economic development. This decline in the average fertility rate of 4.7 children per woman to 2.5 children per woman “is one of the most fundamental social changes that happened in human history. It is therefore especially surprising how very rapidly this transition can indeed happen” (Roser). In addition to this decline, in terms of birth rates, there has been a strong convergence between developed and less developed countries. To examine this idea further, countries that “already had low fertility rates in the 1950s only slightly decreased fertility rates further, while many of the countries that had the highest fertility back then saw a rapid reduction of the number of children per woman” (Roser). The negative correlation between women’s education and fertility is strongly observed across regions and time; however, its interpretation is unclear. Women’s education level could affect fertility through its impact on women’s health and their physical capacity to give birth, children’s health, the number of children desired, and women’s ability to control birth and knowledge of different birth control methods. Each of these mechanisms depends on the individual, institutional, and country circumstances experienced. Their relative importance may change along a country’s economic development process.
Now that the foundation of this occurrence has been formulated, the question becomes: what components have contributed to this rapid change? As previously mentioned, this is the result of a multitude of different contributing variables. On the surface, it can be acknowledged that these declines can be attributed to the empowerment of women, increase in health and well-being of children, technological and economic advancement, growth in access to efficient and quality healthcare, and societal development; however, it is essential that we dive deeper into these ideas. With all things considered, it is understandable how economists view childbearing as an economic decision, where households have to decide between “consuming” children and goods. As we have developed as a world, it is evident that the impact of the this “decision” has spurred a negative correlation between income and fertility–naively hinting at this idea that children are inferior goods.

Section 1: Life Expectancy 
Vast improvements to Public Health such improvement in sanitation, housing, infectious disease control, and education played a significant role in increasing life expectancy over the course of several years. Industrialized countries in the early 19th century, were first to experience increase in life expectancy, while it remained relatively low in the rest of the world. This moment in time reflects the trends we see in our world today. While Public Health advancements contributed to extending life and improving health, these advancements were not distributed globally. While high-income countries have reached a plateau in life expectancy rates, low-income countries have are steadily catching up as access to care expands. 

https://sjbpublichealth.org/200-years-public-health-doubled-life-expectancy/ 
  
  Section 2:  GDP and Fertility Rate
Over the course of human history, we witness strong association among the development of economy and growth or decline of the population. While wealthy countries tend to have less children, and poor countries more children, the relationship between fertility rates and the economy remains dynamic throughout different stages of history. 

Section 3: Advanced Education, Labor Force Participation
There is an interesting link among female education and childbearing. Over the years, women with high educational attainment tend to have fewer children while the opposite is true for those with less to no education. The economic theory of fertility suggests that financial incentives affect reproductive behaviors. Women who are empowered through education tend have children later in life, have higher labor force participation and increased opportunity costs. These women have increased bargaining women within a household, increased access to family planning methods. Dynamic consideration of these different factors is crucial in order to understand association among these variables.


Section 4: Fertility Rate and Infant Mortality 
Infant mortality is defined as the number of children dying before the age of 5. The reduction of child mortality is associated with reduction of fertility. In fact, the child survival hypothesis suggests that when child mortality is reduced, then eventually fertility reduction follows with the net effect of lower growth of population[1].  This demographic transition has varied over time but was most prominent in the nineteenth century.